Move up Copy Files in Build Phases so that programm can be run more than one time without code change:
ERROR: Cycle inside VulkanTutorialFirstTriangle; building could produce
unreliable results.